"""empty message

Revision ID: 5ff9ef5b03b5
Revises: 
Create Date: 2017-01-24 17:42:36.418279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff9ef5b03b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxi',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.REAL(), nullable=True),
    sa.Column('latitude', sa.REAL(), nullable=True),
    sa.Column('speed', sa.REAL(), nullable=True),
    sa.Column('direction', sa.REAL(), nullable=True),
    sa.Column('datetime', sa.DATETIME(), nullable=True),
    sa.Column('previous_status', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.Integer(), nullable=True),
    sa.Column('status_diff', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxi')
    # ### end Alembic commands ###
